import SwiftUI

struct PairingView: View {
    @EnvironmentObject private var app: AppModel
    @Environment(\.dismiss) private var dismiss

    let host: SatelliteHost
    @State private var satellitePIN = ""

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    Label(host.name, systemImage: "desktopcomputer")
                }

                Section("Enter Satellite PIN") {
                    TextField("4-digit PIN", text: $satellitePIN)
                        .keyboardType(.numberPad)
                        .textContentType(.oneTimeCode)
                        .onChange(of: satellitePIN) { _, value in
                            satellitePIN = String(value.filter(\.isNumber).prefix(4))
                        }

                    Text("Enter the 4-digit PIN shown by Satellite on your Windows PC.")
                        .font(.caption)
                        .foregroundStyle(.secondary)

                    Button {
                        Task {
                            await app.pairWithSatellitePIN(host: host, pin: satellitePIN)
                        }
                    } label: {
                        if app.pairingState == .pairingWithSatellitePIN {
                            HStack {
                                ProgressView()
                                Text("Pairing…")
                            }
                            .frame(maxWidth: .infinity)
                        } else {
                            Text("Pair")
                                .frame(maxWidth: .infinity)
                        }
                    }
                    .disabled(
                        satellitePIN.count != 4 ||
                        app.pairingState == .pairingWithSatellitePIN
                    )
                }

                Section("Alternative Approval") {
                    if app.clientPairingPIN.isEmpty {
                        Button("Generate Dish Approval Code") {
                            app.beginPairing(host: host)
                        }

                        Text("Only use this if you want Satellite to approve a code generated by Dish instead.")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    } else {
                        VStack(spacing: 12) {
                            Text("Approve this code on Satellite")
                                .font(.subheadline)
                                .foregroundStyle(.secondary)

                            Text(app.clientPairingPIN)
                                .font(.system(size: 42, weight: .bold, design: .monospaced))
                                .tracking(8)
                                .frame(maxWidth: .infinity)

                            if app.pairingState == .requestingApproval ||
                                app.pairingState == .awaitingApproval {
                                HStack(spacing: 10) {
                                    ProgressView()
                                    Text(
                                        app.pairingState == .requestingApproval
                                            ? "Sending pairing request…"
                                            : "Waiting for approval on Satellite…"
                                    )
                                    .font(.footnote)
                                    .foregroundStyle(.secondary)
                                }
                            }
                        }
                        .padding(.vertical, 6)
                    }
                }

                if let error = app.errorMessage {
                    Section {
                        Text(error)
                            .foregroundStyle(.red)
                    }
                }
            }
            .navigationTitle("Pair with Satellite")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        app.cancelPairing()
                        dismiss()
                    }
                }
            }
            .onChange(of: app.pairingState) { _, state in
                if state == .paired {
                    dismiss()
                }
            }
            .onDisappear {
                if app.pairingState != .paired {
                    app.cancelPairing()
                }
            }
        }
    }
}
